//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp_Service_TEST.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/WebAdd", ReplyAction="http://tempuri.org/IService1/WebAddResponse")]
        int WebAdd(int x, int y);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/WebAdd", ReplyAction="http://tempuri.org/IService1/WebAddResponse")]
        System.Threading.Tasks.Task<int> WebAddAsync(int x, int y);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/WebSoustraction", ReplyAction="http://tempuri.org/IService1/WebSoustractionResponse")]
        int WebSoustraction(int x, int y);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/WebSoustraction", ReplyAction="http://tempuri.org/IService1/WebSoustractionResponse")]
        System.Threading.Tasks.Task<int> WebSoustractionAsync(int x, int y);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/WebMultiply", ReplyAction="http://tempuri.org/IService1/WebMultiplyResponse")]
        int WebMultiply(int x, int y);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/WebMultiply", ReplyAction="http://tempuri.org/IService1/WebMultiplyResponse")]
        System.Threading.Tasks.Task<int> WebMultiplyAsync(int x, int y);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/WebDivision", ReplyAction="http://tempuri.org/IService1/WebDivisionResponse")]
        int WebDivision(int x, int y);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/WebDivision", ReplyAction="http://tempuri.org/IService1/WebDivisionResponse")]
        System.Threading.Tasks.Task<int> WebDivisionAsync(int x, int y);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : WindowsFormsApp_Service_TEST.ServiceReference1.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<WindowsFormsApp_Service_TEST.ServiceReference1.IService1>, WindowsFormsApp_Service_TEST.ServiceReference1.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int WebAdd(int x, int y) {
            return base.Channel.WebAdd(x, y);
        }
        
        public System.Threading.Tasks.Task<int> WebAddAsync(int x, int y) {
            return base.Channel.WebAddAsync(x, y);
        }
        
        public int WebSoustraction(int x, int y) {
            return base.Channel.WebSoustraction(x, y);
        }
        
        public System.Threading.Tasks.Task<int> WebSoustractionAsync(int x, int y) {
            return base.Channel.WebSoustractionAsync(x, y);
        }
        
        public int WebMultiply(int x, int y) {
            return base.Channel.WebMultiply(x, y);
        }
        
        public System.Threading.Tasks.Task<int> WebMultiplyAsync(int x, int y) {
            return base.Channel.WebMultiplyAsync(x, y);
        }
        
        public int WebDivision(int x, int y) {
            return base.Channel.WebDivision(x, y);
        }
        
        public System.Threading.Tasks.Task<int> WebDivisionAsync(int x, int y) {
            return base.Channel.WebDivisionAsync(x, y);
        }
    }
}
